### ISSUE TITLE
Instantiate argmin

### ISSUE THREAD

**Issue by finmod** [AtsushiSakai/argmin.jl#1]
Trying to run argmin locally, it is testing ok. When I try using argmin in the example nonlinear_model_fitting, I obtain this error which is probably connected to the absence of Manifest.toml and Project.toml in the package.

using argmin

ArgumentError: Package argmin [803de2bc-f917-5682-9bbc-4b1ff778c55e] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(::Base.PkgId) at .\loading.jl:982
 [2] require(::Base.PkgId) at .\loading.jl:911
 [3] require(::Module, ::Symbol) at .\loading.jl:906
 [4] top-level scope at In[1]:1

**Comment by AtsushiSakai** [comment]
@finmod  Hi. This is repo is not a Julia package. but I have no time now to do it. Could you fix it? Your PR is wellcome.

**Comment by AtsushiSakai** [comment]
I fixed it. This repo is a julia package.
